AUTOMATIC_MIXED_PRECISION: True

LR: 3e-4
LR_MIN: 2e-5
LR_DECAY_RATE: 0.9
LR_WARMUP_STEPS: 3000

GPUS: 4
DIST_URL: "tcp://127.0.0.1:13252"

BATCH_SIZE: 8
DATA_WORKERS: 6
PREFETCH_FACTOR: 1

WEIGHT_DECAY: 0.05
CLIP_GRAD_NORM: 5.0
FREEZE_ID_BANK_STEP: 40000

LOSS_CE_COEF: 1.0
LOSS_DICE_COEF: 1.0
CE_LOSS_K_VALUE: 0.25
CE_LOSS_K_START: 40000
TOTAL_OPTIMIZATION_STEPS: 80000

TRAIN_SHORT_EDGE_LEN: 480
TRAIN_CROP_SIZE: [464, 464]
TRAIN_SCALE_MIN: 0.7
TRAIN_SCALE_MAX: 1.3

SEQUENTIAL_TRAINING_START: 40000
TRAIN_SEQ_LEN: 5

DAVIS_ROOT: datasets/DAVIS
DAVIS_GAP: 4
DAVIS_GAP_SEQUENTIAL: 4
DAVIS_REPEAT: 5
DAVIS_MERGE_PROB: 0.4
DAVIS_TRAIN_SPLITS:
  - train
  # - val
DAVIS_EVAL_RESOLUTION: 480p
# DAVIS_EVAL_RESOLUTION: Full-Resolution

YTB_ROOT: datasets/YTB
YTB_GAP: 2
YTB_GAP_SEQUENTIAL: 2
YTB_REPEAT: 1
YTB_MERGE_PROB: 0.4

MOSE_ROOT: datasets/MOSE
MOSE_GAP: 4
MOSE_GAP_SEQUENTIAL: 4
MOSE_REPEAT: 1

TENSORBOARD_STEP: 1
STDOUT_STEP: 25
CKPT_STEP: 1000

DAVIS_EVAL_TRAIN_STEP: 10000000000
DAVIS_EVAL_VAL_STEP: 5000
DAVIS_EVAL_TESTDEV_STEP: 10000000000
YTB_EVAL_STEP: 10000000000

CKPT_DIR: checkpoints
VIDEO_DIR: videos
TENSORBOARD_DIR: tensorboard

NUM_CLASSES: 10
# ENCODER_MODEL: MobileNetV2
ENCODER_MODEL: SwinB

ENCODER_FREEZE_STAGES: 2
FLOW_ESTIMATOR_MODEL: GMA
# FLOW_ESTIMATOR_MODEL: FlowFormer
WARPFORMER_DIM: 256
WARPFORMER_ATTENTION_HEADS: 8
WARPFORMER_HIDDEN_SIZE: 1024